# Generated by Django 5.2.5 on 2025-09-01 21:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chave",
                    models.CharField(max_length=100, unique=True, verbose_name="Chave"),
                ),
                ("valor", models.TextField(verbose_name="Valor")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("texto", "Texto"),
                            ("numero", "Número"),
                            ("booleano", "Booleano"),
                            ("data", "Data"),
                            ("email", "E-mail"),
                            ("url", "URL"),
                            ("arquivo", "Arquivo"),
                        ],
                        default="texto",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Descrição"
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        default="geral", max_length=50, verbose_name="Categoria"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data de Criação",
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração",
                "verbose_name_plural": "Configurações",
                "ordering": ["categoria", "chave"],
                "indexes": [
                    models.Index(fields=["chave"], name="core_config_chave_0a8113_idx"),
                    models.Index(
                        fields=["categoria"], name="core_config_categor_6147b8_idx"
                    ),
                    models.Index(fields=["ativo"], name="core_config_ativo_6eb6e7_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "celular",
                    models.CharField(blank=True, max_length=20, verbose_name="Celular"),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="perfis/", verbose_name="Foto"
                    ),
                ),
                (
                    "tema",
                    models.CharField(
                        choices=[
                            ("claro", "Claro"),
                            ("escuro", "Escuro"),
                            ("auto", "Automático"),
                        ],
                        default="claro",
                        max_length=20,
                        verbose_name="Tema",
                    ),
                ),
                (
                    "idioma",
                    models.CharField(
                        default="pt-br", max_length=10, verbose_name="Idioma"
                    ),
                ),
                (
                    "notificacoes_email",
                    models.BooleanField(
                        default=True, verbose_name="Notificações por E-mail"
                    ),
                ),
                (
                    "notificacoes_sistema",
                    models.BooleanField(
                        default=True, verbose_name="Notificações do Sistema"
                    ),
                ),
                (
                    "notificacoes_prazos",
                    models.BooleanField(
                        default=True, verbose_name="Notificações de Prazos"
                    ),
                ),
                (
                    "oab_numero",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Número da OAB"
                    ),
                ),
                (
                    "oab_uf",
                    models.CharField(
                        blank=True, max_length=2, verbose_name="UF da OAB"
                    ),
                ),
                (
                    "especialidades",
                    models.TextField(blank=True, verbose_name="Especialidades"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data de Criação",
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuário",
                "verbose_name_plural": "Perfis de Usuário",
                "ordering": ["usuario__username"],
            },
        ),
        migrations.CreateModel(
            name="Backup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("completo", "Completo"),
                            ("incremental", "Incremental"),
                            ("diferencial", "Diferencial"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("iniciado", "Iniciado"),
                            ("em_progresso", "Em Progresso"),
                            ("concluido", "Concluído"),
                            ("erro", "Erro"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="iniciado",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "tamanho_bytes",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Tamanho (bytes)"
                    ),
                ),
                (
                    "arquivo_backup",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="backups/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["zip", "tar", "gz"]
                            )
                        ],
                        verbose_name="Arquivo de Backup",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Data de Início"
                    ),
                ),
                (
                    "data_fim",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Fim"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "erro_detalhes",
                    models.TextField(blank=True, verbose_name="Detalhes do Erro"),
                ),
                (
                    "automatico",
                    models.BooleanField(default=False, verbose_name="Automático"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Backup",
                "verbose_name_plural": "Backups",
                "ordering": ["-data_inicio"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="core_backup_status_b62d05_idx"
                    ),
                    models.Index(fields=["tipo"], name="core_backup_tipo_8e2bb1_idx"),
                    models.Index(
                        fields=["data_inicio"], name="core_backup_data_in_96f665_idx"
                    ),
                    models.Index(
                        fields=["automatico"], name="core_backup_automat_0b4ec8_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LogSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                        verbose_name="Nível",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("sistema", "Sistema"),
                            ("usuario", "Usuário"),
                            ("processo", "Processo"),
                            ("cliente", "Cliente"),
                            ("documento", "Documento"),
                            ("agenda", "Agenda"),
                            ("financeiro", "Financeiro"),
                            ("seguranca", "Segurança"),
                            ("backup", "Backup"),
                            ("integracao", "Integração"),
                        ],
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                ("acao", models.CharField(max_length=100, verbose_name="Ação")),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Endereço IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "dados_extras",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Dados Extras"
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data de Criação",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log do Sistema",
                "verbose_name_plural": "Logs do Sistema",
                "ordering": ["-data_criacao"],
                "indexes": [
                    models.Index(
                        fields=["usuario"], name="core_logsis_usuario_e3a143_idx"
                    ),
                    models.Index(fields=["nivel"], name="core_logsis_nivel_6983e7_idx"),
                    models.Index(
                        fields=["categoria"], name="core_logsis_categor_6ae4da_idx"
                    ),
                    models.Index(
                        fields=["data_criacao"], name="core_logsis_data_cr_937c2d_idx"
                    ),
                    models.Index(
                        fields=["ip_address"], name="core_logsis_ip_addr_18b3dd_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                ("mensagem", models.TextField(verbose_name="Mensagem")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("info", "Informação"),
                            ("sucesso", "Sucesso"),
                            ("aviso", "Aviso"),
                            ("erro", "Erro"),
                            ("lembrete", "Lembrete"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("sistema", "Sistema"),
                            ("processo", "Processo"),
                            ("prazo", "Prazo"),
                            ("agenda", "Agenda"),
                            ("financeiro", "Financeiro"),
                            ("documento", "Documento"),
                            ("cliente", "Cliente"),
                        ],
                        default="sistema",
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                ("lida", models.BooleanField(default=False, verbose_name="Lida")),
                (
                    "importante",
                    models.BooleanField(default=False, verbose_name="Importante"),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data de Criação",
                    ),
                ),
                (
                    "data_leitura",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Leitura"
                    ),
                ),
                (
                    "data_expiracao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Expiração"
                    ),
                ),
                ("url_acao", models.URLField(blank=True, verbose_name="URL de Ação")),
                (
                    "dados_extras",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Dados Extras"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
                "ordering": ["-data_criacao"],
                "indexes": [
                    models.Index(
                        fields=["usuario"], name="core_notifi_usuario_dbe6e6_idx"
                    ),
                    models.Index(fields=["lida"], name="core_notifi_lida_6a9a29_idx"),
                    models.Index(fields=["tipo"], name="core_notifi_tipo_0b8100_idx"),
                    models.Index(
                        fields=["categoria"], name="core_notifi_categor_a95d1a_idx"
                    ),
                    models.Index(
                        fields=["data_criacao"], name="core_notifi_data_cr_8410e5_idx"
                    ),
                    models.Index(
                        fields=["importante"], name="core_notifi_importa_bab13e_idx"
                    ),
                ],
            },
        ),
    ]
