# Generated by Django 5.2.5 on 2025-09-01 21:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import documentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("processos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, unique=True, verbose_name="Nome"),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "cor",
                    models.CharField(
                        default="#007bff",
                        help_text="Cor em formato hexadecimal (#RRGGBB)",
                        max_length=7,
                        verbose_name="Cor (Hex)",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Categoria de Documento",
                "verbose_name_plural": "Categorias de Documentos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome do Documento"),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("peticao", "Petição"),
                            ("contrato", "Contrato"),
                            ("procuracao", "Procuração"),
                            ("certidao", "Certidão"),
                            ("comprovante", "Comprovante"),
                            ("rg", "RG"),
                            ("cpf", "CPF"),
                            ("cnpj", "CNPJ"),
                            ("comprovante_residencia", "Comprovante de Residência"),
                            ("comprovante_renda", "Comprovante de Renda"),
                            ("laudo", "Laudo"),
                            ("parecer", "Parecer"),
                            ("sentenca", "Sentença"),
                            ("acordao", "Acórdão"),
                            ("outros", "Outros"),
                        ],
                        max_length=30,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to=documentos.models.documento_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "txt",
                                ]
                            )
                        ],
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "tamanho_arquivo",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Tamanho do Arquivo (bytes)"
                    ),
                ),
                (
                    "data_upload",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Data de Upload"
                    ),
                ),
                (
                    "data_vencimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Vencimento"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("arquivado", "Arquivado"),
                            ("vencido", "Vencido"),
                        ],
                        default="ativo",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "confidencial",
                    models.BooleanField(default=False, verbose_name="Confidencial"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "versao",
                    models.PositiveIntegerField(default=1, verbose_name="Versão"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "documento_pai",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versoes",
                        to="documentos.documento",
                        verbose_name="Documento Original",
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="processos.processo",
                        verbose_name="Processo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "ordering": ["-data_upload"],
            },
        ),
        migrations.CreateModel(
            name="HistoricoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("criacao", "Criação"),
                            ("edicao", "Edição"),
                            ("download", "Download"),
                            ("exclusao", "Exclusão"),
                            ("restauracao", "Restauração"),
                        ],
                        max_length=20,
                        verbose_name="Ação",
                    ),
                ),
                ("usuario", models.CharField(max_length=200, verbose_name="Usuário")),
                (
                    "data_acao",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Data da Ação"
                    ),
                ),
                ("detalhes", models.TextField(blank=True, verbose_name="Detalhes")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Endereço IP"
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="documentos.documento",
                        verbose_name="Documento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Documento",
                "verbose_name_plural": "Históricos de Documentos",
                "ordering": ["-data_acao"],
            },
        ),
        migrations.CreateModel(
            name="TagDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=50, unique=True, verbose_name="Nome"),
                ),
                (
                    "cor",
                    models.CharField(
                        default="#6c757d", max_length=7, verbose_name="Cor (Hex)"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "documentos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tags",
                        to="documentos.documento",
                        verbose_name="Documentos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag de Documento",
                "verbose_name_plural": "Tags de Documentos",
                "ordering": ["nome"],
            },
        ),
        migrations.AddIndex(
            model_name="documento",
            index=models.Index(
                fields=["processo"], name="documentos__process_c74313_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documento",
            index=models.Index(
                fields=["cliente"], name="documentos__cliente_5f5745_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documento",
            index=models.Index(fields=["tipo"], name="documentos__tipo_384b87_idx"),
        ),
        migrations.AddIndex(
            model_name="documento",
            index=models.Index(fields=["status"], name="documentos__status_7a8643_idx"),
        ),
        migrations.AddIndex(
            model_name="documento",
            index=models.Index(
                fields=["data_upload"], name="documentos__data_up_9c037f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documento",
            index=models.Index(
                fields=["data_vencimento"], name="documentos__data_ve_4b3ad0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="historicodocumento",
            index=models.Index(
                fields=["documento"], name="documentos__documen_2ccf3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="historicodocumento",
            index=models.Index(
                fields=["data_acao"], name="documentos__data_ac_2b7d41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="historicodocumento",
            index=models.Index(fields=["acao"], name="documentos__acao_12a94a_idx"),
        ),
    ]
