# Generated by Django 5.2.5 on 2025-09-01 21:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Processo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Número deve estar no formato NNNNNNN-DD.AAAA.J.TR.OOOO",
                                regex="^\\d{7}-\\d{2}\\.\\d{4}\\.\\d{1}\\.\\d{2}\\.\\d{4}$",
                            )
                        ],
                        verbose_name="Número do Processo",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("civel", "Cível"),
                            ("criminal", "Criminal"),
                            ("trabalhista", "Trabalhista"),
                            ("tributario", "Tributário"),
                            ("administrativo", "Administrativo"),
                            ("familia", "Família"),
                            ("previdenciario", "Previdenciário"),
                            ("consumidor", "Consumidor"),
                            ("outros", "Outros"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("arquivado", "Arquivado"),
                            ("suspenso", "Suspenso"),
                            ("finalizado", "Finalizado"),
                        ],
                        default="ativo",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "parte_contraria",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Parte Contrária"
                    ),
                ),
                (
                    "tribunal",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Tribunal"
                    ),
                ),
                (
                    "vara",
                    models.CharField(blank=True, max_length=100, verbose_name="Vara"),
                ),
                (
                    "juiz",
                    models.CharField(blank=True, max_length=200, verbose_name="Juiz"),
                ),
                (
                    "advogado_responsavel",
                    models.CharField(
                        max_length=200, verbose_name="Advogado Responsável"
                    ),
                ),
                (
                    "valor_causa",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="Valor da Causa",
                    ),
                ),
                (
                    "data_distribuicao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Distribuição"
                    ),
                ),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data de Cadastro",
                    ),
                ),
                ("resumo", models.TextField(blank=True, verbose_name="Resumo")),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processos",
                        to="clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processo",
                "verbose_name_plural": "Processos",
                "ordering": ["-data_cadastro"],
            },
        ),
        migrations.CreateModel(
            name="Prazo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                (
                    "data_vencimento",
                    models.DateField(verbose_name="Data de Vencimento"),
                ),
                (
                    "data_cumprimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Cumprimento"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("cumprido", "Cumprido"),
                            ("vencido", "Vencido"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("normal", "Normal"),
                            ("alta", "Alta"),
                            ("critica", "Crítica"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "responsavel",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Responsável"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "notificado",
                    models.BooleanField(default=False, verbose_name="Notificado"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prazos",
                        to="processos.processo",
                        verbose_name="Processo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prazo",
                "verbose_name_plural": "Prazos",
                "ordering": ["data_vencimento"],
            },
        ),
        migrations.CreateModel(
            name="Andamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Data"
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("despacho", "Despacho"),
                            ("sentenca", "Sentença"),
                            ("audiencia", "Audiência"),
                            ("peticao", "Petição"),
                            ("recurso", "Recurso"),
                            ("decisao", "Decisão"),
                            ("outros", "Outros"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "responsavel",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Responsável"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="andamentos",
                        to="processos.processo",
                        verbose_name="Processo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Andamento",
                "verbose_name_plural": "Andamentos",
                "ordering": ["-data"],
            },
        ),
        migrations.AddIndex(
            model_name="processo",
            index=models.Index(fields=["numero"], name="processos_p_numero_77bd22_idx"),
        ),
        migrations.AddIndex(
            model_name="processo",
            index=models.Index(
                fields=["cliente"], name="processos_p_cliente_e4dcb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processo",
            index=models.Index(fields=["status"], name="processos_p_status_b5122a_idx"),
        ),
        migrations.AddIndex(
            model_name="processo",
            index=models.Index(fields=["tipo"], name="processos_p_tipo_7b2972_idx"),
        ),
        migrations.AddIndex(
            model_name="processo",
            index=models.Index(fields=["ativo"], name="processos_p_ativo_eadea1_idx"),
        ),
        migrations.AddIndex(
            model_name="prazo",
            index=models.Index(
                fields=["processo"], name="processos_p_process_7a2186_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prazo",
            index=models.Index(
                fields=["data_vencimento"], name="processos_p_data_ve_6b8a9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prazo",
            index=models.Index(fields=["status"], name="processos_p_status_cd084a_idx"),
        ),
        migrations.AddIndex(
            model_name="prazo",
            index=models.Index(
                fields=["prioridade"], name="processos_p_priorid_1b0a6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="andamento",
            index=models.Index(
                fields=["processo"], name="processos_a_process_6a8126_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="andamento",
            index=models.Index(fields=["data"], name="processos_a_data_b9cfb2_idx"),
        ),
        migrations.AddIndex(
            model_name="andamento",
            index=models.Index(fields=["tipo"], name="processos_a_tipo_71c135_idx"),
        ),
    ]
